server {
    listen 80;
    server_name ceyizator.com www.ceyizator.com;

    # Tüm HTTP trafiğini otomatik olarak HTTPS'e yönlendir
    location / {
        return 301 https://$host$request_uri;
    }

    # Certbot yenileme işlemleri için açık kalmalı
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name ceyizator.com www.ceyizator.com;
    resolver 127.0.0.11 valid=10s;
    # SSL Sertifika Yolları
    ssl_certificate /etc/letsencrypt/live/ceyizator.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ceyizator.com/privkey.pem;

    # Güvenlik Ayarları (Best Practices)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Frontend Yönlendirmesi
    location / {
        proxy_pass http://ceyizator-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API Yönlendirmesi

location /api/ {

    set $backend_service "http://ceyizator-backend:5000";
    
    proxy_pass $backend_service;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    
    proxy_read_timeout 90;
    proxy_connect_timeout 90;
}

location /socket.io/ {
    proxy_pass http://ceyizator-backend:5000/socket.io/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}
